### ISSUE TITLE
(get-datum ...) and (port-eof?) do not return expected result 

### ISSUE THREAD

**Issue by bcalco** [IronScheme/IronScheme#111] opened 2021-11-09 20:28 UTC
Hi @leppie,

The following code is expected to return (one #\space (two) #f) but instead returns '(one #\<eof\> (two) #t). 

```scheme
  (define (test-get-datum)
    (let* ([result 
            (let ([sip (open-string-input-port "; a\n\n one (two)\n")])
              (let* ([x1 (get-datum sip)]
                     [c1 (lookahead-char sip)]
                     [x2 (get-datum sip)]
                     [x3 (port-eof? sip)])
                (close-port sip)
                (list x1 c1 x2 x3)))])
      result))
  > (test-get-datum)
(one #<eof> (two) #t)
```

This is from section 7.7.4 in TSPL4, the [(get-datum ...)](https://www.scheme.com/tspl4/io.html#./io:s67) form.  I modified it to make sure the port was closed, but otherwise it's the same. The original code produces the same result:

```
> (let ([sip (open-string-input-port "; a\n\n one (two)\n")])
.   (let* ([x1 (get-datum sip)]
.          [c1 (lookahead-char sip)]
.          [x2 (get-datum sip)])
.     (list x1 c1 x2 (port-eof? sip))))
(one #<eof> (two) #t)
>
```

**Comment by leppie** [comment] 2021-11-10 07:13
Possibly related to https://github.com/IronScheme/IronScheme/issues/13

**Comment by leppie** [comment] 2021-11-10 07:55
The problem is with `(lookahead-char sip)` after you called `(get-datum sip)`. 

`get-datum` is greedy, so `lookahead-char` actually only reads at the end of the file. 

This is a limitation in IronScheme. 

Closing as duplicate of #13

**Closed by leppie** 2021-11-10 07:55 UTC
