### ISSUE TITLE
Document support is required.

### ISSUE THREAD

**Issue by jerrylary** [IronScheme/IronScheme#77] opened 2020-11-01 15:45 UTC
Recently, I was thinking about porting ironscheme to my own software. I used to refer to the relevant programming manuals and guides on codeplex, but now codeplex is down and the original documentation is no longer available. I except you @leppie  can provide ironscheme programming manual and guide, PDF format or GitHub wiki can be. thank you.

**Comment by leppie** [comment] 2020-11-10 11:57
Duplicate of https://github.com/IronScheme/IronScheme/issues/72 

Feel free to submit a PR.

**Closed by leppie** 2020-11-10 11:57 UTC
